name: VTEX Deploy

on:
  push:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy with VTEX Toolbelt
        uses: vtex/action-toolbelt@v8
        with:
          account: YOUR_ACCOUNT
          appKey: ${{ secrets.VTEX_TOOLBELT_KEY }}
          appToken: ${{ secrets.VTEX_TOOLBELT_TOKEN }}
          authenticate: true
          workspace: master
      - name: Deploy app
        run: |
          vtex publish
          vtex deploy -f
          vtex update
